### ISSUE TITLE
A Question about mpc and td-mpc

### ISSUE THREAD

**Issue by Lvwenzhou** [nicklashansen/tdmpc#3]
Thank you for your apply a few days ago. I'm doing something about control the medicine dose with rl. I woder whether the td-mpc can against the mpc with  biologic model. If possible, what's the advantage of td-mpc compared with mpc in this field. It's just my own question.

**Comment by Lvwenzhou** [comment]
In my opinion, the td-mpc combines the mpc planning with rl infinite steps return which is the adavantage against the origin mpc.

**Comment by nicklashansen** [comment]
Correct, one advantage is the return estimates. Another differentiator is the way the model is learned and used. Our model is easy to learn and performs well in practice, but because the model in TD-MPC is a latent model with no reconstruction objective, it might be harder to interpret and enforce e.g. safety constraints in TD-MPC compared to a state-based model as commonly used in MPC, so that is something to keep in mind.

**Comment by Lvwenzhou** [comment]
Thank you so much. By the way I have an idea to combine the biological model which neural network is  hard to study with TD-MPC's method to against the oringinal mpc with that model in my filed. You've done an excellent work. It helps me a lot.

**Comment by Lvwenzhou** [comment]
Well I'm sorry to bother you again. I change the mujoco env into my env. But I find that the return of  `agent.plan` would beyond the [-1,1], but it not happens in mujoco env.

**Comment by nicklashansen** [comment]
Happy to help, good luck with your project!
